class ReportGenerator:

    def generate(self, static_report, ai_report):

        report = f"""
# SentinelAI Security Report

## Static Analysis
{static_report}

---

## AI Security Analysis
{ai_report}

---

Generated by SentinelAI
"""

        return report
